// Angular/src/app/components/appointmentInfo/appointmentInfo.component.ts
import { Component, Input } from '@angular/core';
import { Appointment } from 'devextreme/ui/scheduler';

@Component({
  selector: 'appointment-info',
  templateUrl: 'appointmentInfo.component.html',
  styleUrls: ['appointmentInfo.component.css'],
})

export class AppointmentInfo {
  @Input() data: Appointment;

  color: string;

  ngOnInit() {
    this.data['colorDef'].done((color: string) => this.color = color);
  }
}

<div class="tooltip">
  <div class='marker' [style.background]="color"></div>
  <div>
    <p>{{ data.text }}</p>
    <p>{{ data.startDate  }} - {{ data.endDate }}</p>
  </div>
</div>

// Vue/src/components/AppointmentInfo.vue
<template #AppointmentInfo="{ data }">
  <div class="tooltip">
    <div class="marker" :style="`background: ${color}`"/>
    <div>
      <p>{{ data.text }}</p>
      <p>{{ `${data.startDate} - ${data.endDate}` }}</p>
    </div>
  </div>
</template>

<script>
export default {
  created() {
    this.data.colorDef.done((color) => this.color = color);
  },
  props: {
    data: {
      type: Object,
      default: () => {},
    }
  },
  data() {
    return {
      color: '',
    }
  },
}
</script>

<style scoped>

</style>
