// React/src/App.js
import React, {useCallback, useState} from 'react';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css';

import Scheduler from 'devextreme-react/scheduler';
import List from 'devextreme-react/list';

import AppointmentsInfo from './components/AppointmentsInfo';
import {data, resources} from './data';
import {formatDate} from './utils';

const App = () => {
    const [tooltipItems, setTooltipItems] = useState([])
    const currentDate = new Date(2021, 5, 2);

    const onAppointmentTooltipShowing = useCallback((e) => {
        e.cancel = true;
        const {appointments} = e;
        const res = appointments.map((item) => {
            return {
                text: item.appointmentData.text,
                colorDef: item.color,
                startDate: formatDate(item.appointmentData.startDate),
                endDate: formatDate(item.appointmentData.endDate),
            }
        });
        setTooltipItems(res);
    }, []);

    return (
        <div className='container'>
            <List
                width='33%'
                dataSource={tooltipItems}
                itemComponent={AppointmentsInfo}
            />
            <Scheduler
                dataSource={data}
                currentView='week'
                currentDate={currentDate}
                firstDayOfWeek={1}
                startDayHour={15}
                endDayHour={20}
                showAllDayPanel={false}
                height={600}
                width='66%'
                resources={resources}
                onAppointmentTooltipShowing={onAppointmentTooltipShowing}
            >
            </Scheduler>
        </div>
    )
}

export default App;

// Vue/src/App.vue
<template>
  <div class="container">
    <DxList
        width="33%"
        :data-source="tooltipItems"
        item-template="AppointmentInfo"
    >
      <template #AppointmentInfo="{data: tooltipItems}">
        <AppointmentInfo :data="tooltipItems"/>
      </template>
    </DxList>
    <DxScheduler
        current-view="week"
        width="66%"
        :data-source="dataSource"
        :current-date="currentDate"
        :resources="resources"
        :height="600"
        :start-day-hour="15"
        :end-day-hour="20"
        :on-appointment-tooltip-showing="onAppointmentTooltipShowing"
    >
    </DxScheduler>
  </div>
</template>

<script>
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import { DxScheduler } from 'devextreme-vue/scheduler';
import { DxList } from 'devextreme-vue/list';
import { data, resources } from './data.js';
import Utils from './utils.js';
import './style.css';
import AppointmentInfo from '@/components/AppointmentInfo';

export default {
  name: 'App',
  components: {
    AppointmentInfo,
    DxScheduler,
    DxList,
  },
  data() {
    return {
      currentDate: new Date(2021, 5, 2),
      dataSource: data,
      resources: resources,
      tooltipItems: [],
    };
  },
  methods: {
    onAppointmentTooltipShowing: function (e) {
      e.cancel = true;
      const {appointments} = e;
      const res = appointments.map((item) => {
        return {
          text: item.appointmentData.text,
          colorDef: item.color,
          startDate: Utils.formatDate(item.appointmentData.startDate),
          endDate: Utils.formatDate(item.appointmentData.endDate),
        }
      });
      this.tooltipItems = res;
    },
  }
};
</script>
