// React/src/App.js
import React, {useCallback, useState} from 'react';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css';

import Scheduler from 'devextreme-react/scheduler';
import List from 'devextreme-react/list';

import AppointmentsInfo from './components/AppointmentsInfo';
import {data, resources} from './data';
import {formatDate} from './utils';

const App = () => {
    const [tooltipItems, setTooltipItems] = useState([])
    const currentDate = new Date(2021, 5, 2);

    const onAppointmentTooltipShowing = useCallback((e) => {
        e.cancel = true;
        const {appointments} = e;
        const res = appointments.map((item) => {
            return {
                text: item.appointmentData.text,
                colorDef: item.color,
                startDate: formatDate(item.appointmentData.startDate),
                endDate: formatDate(item.appointmentData.endDate),
            }
        });
        setTooltipItems(res);
    }, []);

    return (
        <div className='container'>
            <List
                width='33%'
                dataSource={tooltipItems}
                itemComponent={AppointmentsInfo}
            />
            <Scheduler
                dataSource={data}
                currentView='week'
                currentDate={currentDate}
                firstDayOfWeek={1}
                startDayHour={15}
                endDayHour={20}
                showAllDayPanel={false}
                height={600}
                width='66%'
                resources={resources}
                onAppointmentTooltipShowing={onAppointmentTooltipShowing}
            >
            </Scheduler>
        </div>
    )
}

export default App;

// Angular/src/app/app.component.ts
import { Component, enableProdMode } from '@angular/core';
import {
  Appointment,
  AppointmentTooltipShowingAppointmentInfo,
  AppointmentTooltipShowingEvent
} from 'devextreme/ui/scheduler';
import { employees, data } from './data';

if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}

@Component({
  selector: 'demo-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
})
export class AppComponent {
  dataSource = data;
  currentDate: Date = new Date(2021, 5, 2);
  resourcesDataSource = employees;
  tooltipItems: Appointment[] = [];

  onAppointmentTooltipShowing(e: AppointmentTooltipShowingEvent) {
    e.cancel = true;
    const {appointments} = e;
    const res = appointments.map((item: AppointmentTooltipShowingAppointmentInfo) => {

      return {
        text: item.appointmentData.text,
        colorDef: item.color,
        startDate: this.formatDate(item.appointmentData.startDate as Date),
        endDate: this.formatDate(item.appointmentData.endDate as Date),
      }
    });

    this.tooltipItems = res;
  }

  private formatDate(date: Date) {
    return `${date.getHours()}:${date.getMinutes()}`
  }
}

<div id="container" class="container">
  <dx-list
    width="33%"
    [dataSource]="tooltipItems"
    itemTemplate="AppointmentInfo"
  >
    <div *dxTemplate="let item of 'AppointmentInfo'">
      <appointment-info
        [data]="item"
      >
      </appointment-info>
    </div>
  </dx-list>
  <dx-scheduler
    width="66%"
    currentView="week"
    [dataSource]="dataSource"
    [views]="['week']"
    [currentDate]="currentDate"
    [firstDayOfWeek]="1"
    [startDayHour]="15"
    [endDayHour]="50"
    [showAllDayPanel]="false"
    [height]="600"
    (onAppointmentTooltipShowing)="onAppointmentTooltipShowing($event)"
  >
    <dxi-resource
      fieldExpr="employeeID"
      [allowMultiple]="false"
      [dataSource]="resourcesDataSource"
      label="Employee"
    >
    </dxi-resource>
  </dx-scheduler>
</div>
